# Generated by Django 4.2.18 on 2025-02-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_policy_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=25),
        ),
    ]
