# Generated by Django 4.2.18 on 2025-02-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_risk_alter_policy_status_policy_risks'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='description',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
