# Generated by Django 4.2.18 on 2025-02-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_policyversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='title',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
