# Generated by Django 4.2.18 on 2025-02-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_policyversion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='version_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
