# Generated by Django 4.2.18 on 2025-02-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_policy_version_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='version_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='notes',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
    ]
