# Generated by Django 4.2.18 on 2025-02-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_alter_policy_version_count_alter_policyversion_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyversion',
            name='risks',
            field=models.ManyToManyField(null=True, to='security.risk'),
        ),
    ]
