# Generated by Django 4.2.18 on 2025-02-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_alter_policyversion_risks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyversion',
            name='notes',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='risks',
            field=models.ManyToManyField(to='security.risk'),
        ),
    ]
