# Generated by Django 4.2.18 on 2025-02-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_alter_policyversion_notes_alter_policyversion_risks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('reference_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='compliance_standards',
            field=models.ManyToManyField(to='security.compliancestandard'),
        ),
    ]
