# Generated by Django 4.2.18 on 2025-02-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_compliancestandard_policy_compliance_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='compliance_standards',
            field=models.ManyToManyField(to='security.compliancestandard'),
        ),
    ]
