# Generated by Django 4.2.18 on 2025-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_policyversion_compliance_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancestandard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
